### ISSUE TITLE
communictation with pdb down

### ISSUE THREAD

**Issue by grandrea** [Rappsilber-Laboratory/build-xiview#109]
Hello,
I tried to upload pdb via code today and got this error
<img width="573" alt="pdb" src="https://github.com/Rappsilber-Laboratory/build-xiview/assets/44289027/ede9bea4-f3d5-4064-b300-9c916bfd105d">

**Comment by colin-combe** [comment]
mmtf.rcsb.org seems to be down

let's give it a bit to see if it comes back...

**Comment by colin-combe** [comment]
thanks error message

**Comment by colin-combe** [comment]
ok... guess its not coming back https://www.rcsb.org/news/feature/663129f765d8a8cacaf76f9f

**Comment by colin-combe** [comment]
so i'm gonna have to fix this

**Comment by colin-combe** [comment]
its an NGL problem https://github.com/nglviewer/ngl/issues/1045

@grandrea - you remember this thing whereby i hacked NGL so that chainnames could be 2 characters instead of 1? (https://github.com/colin-combe/ngl/commit/71873ed45ee67cae5871235e59a4a49a43418cd6)

How important is that still? It did break some things in NGL, just not things we used much.

In other words, what if I just updated to most recent version of NGL to fix this? Do you think that would mess things up for people?

**Comment by colin-combe** [comment]
it should be that this is fixed in the latest version of NGL on npm (https://www.npmjs.com/package/ngl).

So i should be able to fix this in xiVIEW and tidy some stuff up by importing NGL straight from npm (which xiVIEW already uses for managing JS dependencies).

But then you lose that 2 char hack. 

Awaiting your input.

**Comment by grandrea** [comment]
bye bye 2 char hack.

**Comment by grandrea** [comment]
(that work is done afaik)

**Comment by colin-combe** [comment]
> So i should be able to fix this in xiVIEW and tidy some stuff up by importing NGL straight from npm

good that we have tests, because they now fail

**Comment by colin-combe** [comment]
Things working again now?

**Comment by grandrea** [comment]
yes, all good
